<?php
/**
 *  Autoloader function generated by crodas/Autoloader
 *
 *  https://github.com/crodas/Autoloader
 *
 *  This is a generated file, do not modify it.
 */

spl_autoload_register(function ($class) {
    /*
        This array has a map of (class => file)
    */

    // classes {{{
    static $classes = array (
  'serviceprovider\\notfoundexception' => '/NotFoundException.php',
  'serviceprovider\\parser\\yaml' => '/Parser/Yaml.php',
  'serviceprovider\\compiler\\servicecall' => '/Compiler/ServiceCall.php',
  'serviceprovider\\parser' => '/Parser.php',
  'serviceprovider\\provider' => '/Provider.php',
);
    // }}}


    $class = strtolower($class);
    if (isset($classes[$class])) {

        if (!class_exists($class, false)) {

            require __DIR__  . $classes[$class];

        }
        return true;
    }

    return false;
});


